services:
  abs-bigfinish:
    build: .
    container_name: abs-bigfinish
    restart: unless-stopped
    ports:
      - '7777:7777'
    environment:
      - NODE_ENV=production
      - HARDCOVER_TOKEN=${HARDCOVER_TOKEN}
      # See https://lazylibrarian.gitlab.io/config_importing/
      - GOODREADS_API_KEY=${GOODREADS_API_KEY}
    volumes:
      - .:/app/data
    # This container runs by default as 1000:1000 user.
    # If you did not create the data folder, yet and run the docker daemon as another user/root, either set the permissions of the data folder accordingly (1000:1000) or adjust the user here.
    # user: 0:0
